labs/urls.py
from django.urls import path

from . import views as labs_views

app_name = "labs"

urlpatterns = [
    # Generals Views
    path('', labs_views.home_view, name="home"),
    path('intro/', labs_views.intro_view, name="intro"),
    path('pricing/', labs_views.pricing_view, name="pricing"),
    path('contact/', labs_views.contact_view, name="contact"),
    # Laboratories Views
    path('tests-concrete/', labs_views.labs_concrete_view, name="concrete"),
    path('tests-material/', labs_views.labs_material_view, name="material"),
    path('tests-soil/', labs_views.labs_soil_view, name="soil"),
    # Sectors Views
        # Client Sector 
    path('sectors-client/', labs_views.sector_client_view, name="client"),
    path('sectors-client-info/', labs_views.sector_client_info_view, name="client_info"),
    path('sectors-client-equips-concrete/', labs_views.client_equips_concrete_view, name="client_equips_concrete"),
    path('sectors-client-equips-material/', labs_views.client_equips_material_view, name="client_equips_material"),
    path('sectors-client-equips-soil/', labs_views.client_equips_soil_view, name="client_equips_soil"),
        # Bach Sector
    path('sectors-bach/', labs_views.sector_bach_view, name="bach"),
    path('sectors-bach-info/', labs_views.sector_bach_info_view, name="bach_info"),
    path('sectors-bach-equips-concrete/', labs_views.bach_equips_concrete_view, name="bach_equips_concrete"),
    path('sectors-bach-equips-material/', labs_views.bach_equips_material_view, name="bach_equips_material"),
    path('sectors-bach-equips-soil/', labs_views.bach_equips_soil_view, name="bach_equips_soil"),
        # Student Sector
    path('sectors-student/', labs_views.sector_student_view, name="student"),
    path('sectors-student-info/', labs_views.sector_student_info_view, name="student_info"),
    path('sectors-student-equips-concrete/', labs_views.student_equips_concrete_view, name="student_equips_concrete"),
    path('sectors-student-equips-material/', labs_views.student_equips_material_view, name="student_equips_material"),
    path('sectors-student-equips-soil/', labs_views.student_equips_soil_view, name="student_equips_soil"),
        # General Sector
            # Info
    path('general/', labs_views.general_view, name="general"),
    path('general-personal/', labs_views.general_personal_view, name="general_personal"),
    path('general-clients/', labs_views.general_clients_view, name="general_clients"),
    path('general-ref-per/', labs_views.general_ref_per_view, name="general_ref_per"),
    path('general-construction/', labs_views.general_construction_view, name="general_construction"),
    path('general-bach/', labs_views.general_bach_view, name="general_bach"),
    path('general-thesis/', labs_views.general_thesis_view, name="general_thesis"),
    path('general-student/', labs_views.general_student_view, name="general_student"),
    path('general-equips/', labs_views.general_equips_view, name="general_equips"),
            # Info Tests Concrete
    path('general-diamond-pice-break/', labs_views.general_diamond_pice_break, name="general_diamond_pice_break"),
    path('general-pice-break/', labs_views.general_pice_break, name="general_pice_break"),
    path('general-prism-break/', labs_views.general_prism_break, name="general_prism_break"),
            # Info Tests Material
    path('general-brick-type/', labs_views.general_brick_type, name="general_brick_type"),
    path('general-masonry-compression/', labs_views.general_masonry_compression, name="general_masonry_compression"),
    path('general-wood-compression/', labs_views.general_wood_compression, name="general_wood_compression"),
            # Info Tests Soil
    path('general-equivalent/', labs_views.general_equivalent, name="general_equivalent"),
    path('general-fine-material/', labs_views.general_fine_material, name="general_fine_material"),
    path('general-granulometric-global/', labs_views.general_granulometric_global, name="general_granulometric_global"),
    path('general-limit/', labs_views.general_limit, name="general_limit"),
    path('general-moisture-content/', labs_views.general_moisture_content, name="general_moisture_content"),
    path('general-proctor-m/', labs_views.general_proctor_m, name="general_proctor_m"),
    path('general-sand-cone/', labs_views.general_sand_cone, name="general_sand_cone"),
    path('general-specific_gravity/', labs_views.general_specific_gravity, name="general_specific_gravity"),
]

labs/views/generals.py
from django.shortcuts import render

from accounts.models import *

# Create your views here.

def intro_view(request):
    return render(request, 'labs/generals/intro.html')

def home_view(request):
    return render(request, 'labs/generals/home.html')


def pricing_view(request):
    return render(request, 'labs/generals/pricing.html')


def contact_view(request):
    return render(request, 'labs/generals/contact.html')

templates/labs/sectors/general/general.html
{% extends "base_normal.html" %}

{% block content %}
<div class="my-5">
  <div class="row">
    <div class="col-md-3 col-lg-3">
      {% include "labs/sectors/general/sidenav_general.html" %}
    </div>
    <div class="col-md-9 col-lg-9 mt-4">
                <!--Grid row-->
        <div class="row">
                    
            <!--Grid column-->
            <div class="col-md-6 mb-4">  
              <!-- Card -->
              <div class="card">
                    <!-- Content -->
                    <a href="#">
                      <div class="text-white d-flex h-100 mask success-color-dark">
                        <div class="align-self-center p-3">
                          <h3 class="card-title">Personal</h3>
                          <p class="lead ">Más detalles<i class="fas fa-angle-double-right pl-2"></i></p>
                        </div>
                      </div>
                    </a>    
              </div>
              <!-- Card -->
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">  
              <!-- Card -->
              <div class="card">
                    <!-- Content -->
                    <a href="#">
                      <div class="text-white d-flex h-100 mask warning-color-dark">
                        <div class="align-self-center p-3">
                          <h3 class="card-title">Equipos</h3>
                          <p class="lead ">Más detalles<i class="fas fa-angle-double-right pl-2"></i></p>
                        </div>
                      </div>
                    </a>    
              </div>
              <!-- Card -->
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">  
              <!-- Card -->
              <div class="card">
                    <!-- Content -->
                    <a href="#">
                      <div class="text-white d-flex h-100 mask primary-color-dark">
                        <div class="align-self-center p-3">
                          <h3 class="card-title">Nada</h3>
                          <p class="lead ">Más detalles<i class="fas fa-angle-double-right pl-2"></i></p>
                        </div>
                      </div>
                    </a>    
              </div>
              <!-- Card -->
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">  
              <!-- Card -->
              <div class="card">
                    <!-- Content -->
                    <a href="#">
                      <div class="text-white d-flex h-100 mask danger-color-dark">
                        <div class="align-self-center p-3">
                          <h3 class="card-title">Nada</h3>
                          <p class="lead  ">Más detalles<i class="fas fa-angle-double-right pl-2"></i></p>
                        </div>
                      </div>
                    </a>    
              </div>
              <!-- Card -->
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->      
    </div>
  </div>
</div>
{% endblock content %}

templates/labs/sectors/general/sidenav_general.html
<div id="menu">
    <div class="list-group">
      <a href="#" class="list-group-item unique-color white-text" data-toggle="collapse" data-target="#list-one" data-parent="#menu"><i class="fas fa-chart-line pr-2"></i>Información General</a>
      <div class="list-group collapse" id="list-one">
        <a class="list-group-item" href="{% url 'labs:general_personal' %}"><i class="fas fa-angle-double-right pr-2"></i>Personal del Laboratorio</a>
        <a class="list-group-item" href="{% url 'labs:general_clients' %}"><i class="fas fa-angle-double-right pr-2"></i>Clientes</a>
        <a class="list-group-item" href="{% url 'labs:general_ref_per' %}"><i class="fas fa-angle-double-right pr-2"></i>Persona de Referencia</a>
        <a class="list-group-item" href="{% url 'labs:general_construction' %}"><i class="fas fa-angle-double-right pr-2"></i>Construcciones</a>
        <a class="list-group-item" href="{% url 'labs:general_bach' %}"><i class="fas fa-angle-double-right pr-2"></i>Tesistas</a>
        <a class="list-group-item" href="{% url 'labs:general_thesis' %}"><i class="fas fa-angle-double-right pr-2"></i>Tesis</a>
        <a class="list-group-item" href="{% url 'labs:general_student' %}"><i class="fas fa-angle-double-right pr-2"></i>Estudiantes</a>
        <a class="list-group-item" href="{% url 'labs:general_equips' %}"><i class="fas fa-angle-double-right pr-2"></i>Equipos</a>
        <a class="list-group-item" href="#!"><i class="fas fa-angle-double-right pr-2"></i>Herramientas</a>
      </div>
      <a href="#" class="list-group-item unique-color white-text" data-toggle="collapse" data-target="#list-two" data-parent="#menu"><i class="fas fa-chart-line pr-2"></i>Ensayos del Lab. de Tecnología del Concreto</a>
      <div class="list-group collapse" id="list-two">
        <a class="list-group-item" href="{% url 'labs:general_pice_break' %}"><i class="fas fa-angle-double-right pr-2"></i>Compresión de Testigos</a>
        <a class="list-group-item" href="{% url 'labs:general_prism_break' %}"><i class="fas fa-angle-double-right pr-2"></i>Compresión de Prismas</a>
        <a class="list-group-item" href="{% url 'labs:general_diamond_pice_break' %}"><i class="fas fa-angle-double-right pr-2"></i>Extracción y Compresión de Testigos Diamantinos</a>
      </div>
      <a href="#" class="list-group-item unique-color white-text" data-toggle="collapse" data-target="#list-three" data-parent="#menu"><i class="fas fa-chart-line pr-2"></i>Ensayos del Lab. de Materiales de Construcción</a>
      <div class="list-group collapse" id="list-three">
        <a class="list-group-item" href="{% url 'labs:general_brick_type' %}"><i class="fas fa-angle-double-right pr-2"></i>Determinación de Propiedades de Unidades de Ladrillo</a>
        <a class="list-group-item" href="{% url 'labs:general_masonry_compression' %}"><i class="fas fa-angle-double-right pr-2"></i>Compresión de Pilas de Ladrillo</a>
        <a class="list-group-item" href="{% url 'labs:general_wood_compression' %}"><i class="fas fa-angle-double-right pr-2"></i>Madera Compresión Simple</a>
      </div>
      <a href="#" class="list-group-item unique-color white-text" data-toggle="collapse" data-target="#list-four" data-parent="#menu"><i class="fas fa-chart-line pr-2"></i>Ensayos del Lab. de Suelos</a>
      <div class="list-group collapse" id="list-four">
        <a class="list-group-item" href="{% url 'labs:general_equivalent' %}" ><i class="fas fa-angle-double-right pr-2"></i>Determinación del Equivalente de Arena</a>
        <a class="list-group-item" href="{% url 'labs:general_fine_material' %}" ><i class="fas fa-angle-double-right pr-2"></i>Material Más Fino Tamiz 75μm</a>
        <a class="list-group-item" href="{% url 'labs:general_granulometric_global' %}" ><i class="fas fa-angle-double-right pr-2"></i>Clasificación de Suelos - Granulometría Global</a>
        <a class="list-group-item" href="{% url 'labs:general_limit' %}" ><i class="fas fa-angle-double-right pr-2"></i>Límite Líquido y Límite Plástico</a>
        <a class="list-group-item" href="{% url 'labs:general_moisture_content' %}" ><i class="fas fa-angle-double-right pr-2"></i>Contenido de Humedad de Suelos</a>
        <a class="list-group-item" href="{% url 'labs:general_proctor_m' %}" ><i class="fas fa-angle-double-right pr-2"></i>Proctor Modificado MTC E115</a>
        <a class="list-group-item" href="{% url 'labs:general_sand_cone' %}" ><i class="fas fa-angle-double-right pr-2"></i>Densidad Húmeda, Metodo Cono de Arena</a>
        <a class="list-group-item" href="{% url 'labs:general_specific_gravity' %}" ><i class="fas fa-angle-double-right pr-2"></i>Gravedad Especifica de los Suelos (Picometro de Agua)</a>
      </div>
    </div>
</div>