labs/urls.py
from django.urls import path

from . import views as labs_views

app_name = "labs"

urlpatterns = [
    # Generals Views
    path('', labs_views.home_view, name="home"),
    path('intro/', labs_views.intro_view, name="intro"),
    path('pricing/', labs_views.pricing_view, name="pricing"),
    path('contact/', labs_views.contact_view, name="contact"),
    # Laboratories Views
    path('tests-concrete/', labs_views.labs_concrete_view, name="concrete"),
    path('tests-material/', labs_views.labs_material_view, name="material"),
    path('tests-soil/', labs_views.labs_soil_view, name="soil"),
    # Sectors Views
        # Client Sector 
    path('sectors-client/', labs_views.sector_client_view, name="client"),
    path('sectors-client-info/', labs_views.sector_client_info_view, name="client_info"),
    path('sectors-client-equips-concrete/', labs_views.client_equips_concrete_view, name="client_equips_concrete"),
    path('sectors-client-equips-material/', labs_views.client_equips_material_view, name="client_equips_material"),
    path('sectors-client-equips-soil/', labs_views.client_equips_soil_view, name="client_equips_soil"),
        # Bach Sector
    path('sectors-bach/', labs_views.sector_bach_view, name="bach"),
    path('sectors-bach-info/', labs_views.sector_bach_info_view, name="bach_info"),
    path('sectors-bach-equips-concrete/', labs_views.bach_equips_concrete_view, name="bach_equips_concrete"),
    path('sectors-bach-equips-material/', labs_views.bach_equips_material_view, name="bach_equips_material"),
    path('sectors-bach-equips-soil/', labs_views.bach_equips_soil_view, name="bach_equips_soil"),
        # Student Sector
    path('sectors-student/', labs_views.sector_student_view, name="student"),
    path('sectors-student-info/', labs_views.sector_student_info_view, name="student_info"),
    path('sectors-student-equips-concrete/', labs_views.student_equips_concrete_view, name="student_equips_concrete"),
    path('sectors-student-equips-material/', labs_views.student_equips_material_view, name="student_equips_material"),
    path('sectors-student-equips-soil/', labs_views.student_equips_soil_view, name="student_equips_soil"),
        # General Sector
            # Info
    path('general/', labs_views.general_view, name="general"),
    path('general-personal/', labs_views.general_personal_view, name="general_personal"),
    path('general-clients/', labs_views.general_clients_view, name="general_clients"),
    path('general-ref-per/', labs_views.general_ref_per_view, name="general_ref_per"),
    path('general-construction/', labs_views.general_construction_view, name="general_construction"),
    path('general-bach/', labs_views.general_bach_view, name="general_bach"),
    path('general-thesis/', labs_views.general_thesis_view, name="general_thesis"),
    path('general-student/', labs_views.general_student_view, name="general_student"),
    path('general-equips/', labs_views.general_equips_view, name="general_equips"),
            # Info Tests Concrete
    path('general-diamond-pice-break/', labs_views.general_diamond_pice_break, name="general_diamond_pice_break"),
    path('general-pice-break/', labs_views.general_pice_break, name="general_pice_break"),
    path('general-prism-break/', labs_views.general_prism_break, name="general_prism_break"),
            # Info Tests Material
    path('general-brick-type/', labs_views.general_brick_type, name="general_brick_type"),
    path('general-masonry-compression/', labs_views.general_masonry_compression, name="general_masonry_compression"),
    path('general-wood-compression/', labs_views.general_wood_compression, name="general_wood_compression"),
            # Info Tests Soil
    path('general-equivalent/', labs_views.general_equivalent, name="general_equivalent"),
    path('general-fine-material/', labs_views.general_fine_material, name="general_fine_material"),
    path('general-granulometric-global/', labs_views.general_granulometric_global, name="general_granulometric_global"),
    path('general-limit/', labs_views.general_limit, name="general_limit"),
    path('general-moisture-content/', labs_views.general_moisture_content, name="general_moisture_content"),
    path('general-proctor-m/', labs_views.general_proctor_m, name="general_proctor_m"),
    path('general-sand-cone/', labs_views.general_sand_cone, name="general_sand_cone"),
    path('general-specific_gravity/', labs_views.general_specific_gravity, name="general_specific_gravity"),
]

tests_soil/urls.py
from django.urls import path

from . import views as tests_soil_views

app_name = "tests_soil"

urlpatterns = [
    # General views Concrete
    path('info/', tests_soil_views.tests_soil_info_view, name="info"),
    path('equips/', tests_soil_views.tests_soil_equips_view, name="equips"),
    path('guides/', tests_soil_views.tests_soil_guides_view, name="guides"),
    path('teachers/', tests_soil_views.tests_soil_teachers_view, name="teachers"),
    # Limit CRUD and PDF
    path('limit/', tests_soil_views.limit_list, name="limit_list"),
    path('limit/create/', tests_soil_views.limit_create, name="limit_create"),
    path('limit/<int:id>/update/', tests_soil_views.limit_update, name="limit_update"),
    path('limit/<int:id>/detail/', tests_soil_views.limit_detail, name="limit_detail"),
    path('limit/<int:id>/delete/', tests_soil_views.limit_delete, name="limit_delete"),
    path('limit/<int:id>/pdf/', tests_soil_views.limit_pdf, name="limit_pdf"),
        # Liquid and Plastic CRUD
    path('liquid/save/<int:id>/', tests_soil_views.liquid_save, name="liquid_save"),
    path('plastic/save/<int:id>/', tests_soil_views.plastic_save, name="plastic_save"),
    # Fine Material CRUD and PDF
    path('fine-material/', tests_soil_views.fine_material_list, name="fine_material_list"),
    path('fine-material/create/', tests_soil_views.fine_material_create, name="fine_material_create"),
    path('fine-material/<int:id>/update/', tests_soil_views.fine_material_update, name="fine_material_update"),
    path('fine-material/<int:id>/detail/', tests_soil_views.fine_material_detail, name="fine_material_detail"),
    path('fine-material/<int:id>/delete/', tests_soil_views.fine_material_delete, name="fine_material_delete"),
    path('fine-material/<int:id>/pdf/', tests_soil_views.fine_material_pdf, name="fine_material_pdf"),
    # Equivalent CRUD and PDF
    path('equivalent/', tests_soil_views.equivalent_list, name="equivalent_list"),
    path('equivalent/create/', tests_soil_views.equivalent_create, name="equivalent_create"),
    path('equivalent/<int:id>/update/', tests_soil_views.equivalent_update, name="equivalent_update"),
    path('equivalent/<int:id>/detail/', tests_soil_views.equivalent_detail, name="equivalent_detail"),
    path('equivalent/<int:id>/delete/', tests_soil_views.equivalent_delete, name="equivalent_delete"),
    path('equivalent/<int:id>/pdf/', tests_soil_views.equivalent_pdf, name="equivalent_pdf"),
        # Equiv CRUD
    path('equiv/save/<int:id>/', tests_soil_views.equiv_save, name="equiv_save"),
    # Proctor M CRUD and PDF
    path('proctor-m/', tests_soil_views.proctor_m_list, name="proctor_m_list"),
    path('proctor-m/create/', tests_soil_views.proctor_m_create, name="proctor_m_create"),
    path('proctor-m/<int:id>/update/', tests_soil_views.proctor_m_update, name="proctor_m_update"),
    path('proctor-m/<int:id>/detail/', tests_soil_views.proctor_m_detail, name="proctor_m_detail"),
    path('proctor-m/<int:id>/delete/', tests_soil_views.proctor_m_delete, name="proctor_m_delete"),
    path('proctor-m/<int:id>/pdf/', tests_soil_views.proctor_m_pdf, name="proctor_m_pdf"),
        # Density CRUD
    path('density/save/<int:id>/', tests_soil_views.density_save, name="density_save"),
    # path('saturation/save/<int:id>/', tests_soil_views.saturation_save, name="saturation_save"),
    path('correction/save/<int:id>/', tests_soil_views.correction_save, name="correction_save"),
    # Moisture Content CRUD and PDF
    path('moisture-content/', tests_soil_views.moisture_content_list, name="moisture_content_list"),
    path('moisture-content/create/', tests_soil_views.moisture_content_create, name="moisture_content_create"),
    path('moisture-content/<int:id>/update/', tests_soil_views.moisture_content_update, name="moisture_content_update"),
    path('moisture-content/<int:id>/detail/', tests_soil_views.moisture_content_detail, name="moisture_content_detail"),
    path('moisture-content/<int:id>/delete/', tests_soil_views.moisture_content_delete, name="moisture_content_delete"),
    path('moisture-content/<int:id>/pdf/', tests_soil_views.moisture_content_pdf, name="moisture_content_pdf"),
        # Moisture Material CRUD
    path('moisture-material/save/<int:id>/', tests_soil_views.moisture_material_save, name="moisture_material_save"),
    # Specific Gravity CRUD and PDF
    path('specific-gravity/', tests_soil_views.specific_gravity_list, name="specific_gravity_list"),
    path('specific-gravity/create/', tests_soil_views.specific_gravity_create, name="specific_gravity_create"),
    path('specific-gravity/<int:id>/update/', tests_soil_views.specific_gravity_update, name="specific_gravity_update"),
    path('specific-gravity/<int:id>/detail/', tests_soil_views.specific_gravity_detail, name="specific_gravity_detail"),
    path('specific-gravity/<int:id>/delete/', tests_soil_views.specific_gravity_delete, name="specific_gravity_delete"),
    path('specific-gravity/<int:id>/pdf/', tests_soil_views.specific_gravity_pdf, name="specific_gravity_pdf"),
        # Fraction Pass and Retained CRUD
    path('fraction-pass/save/<int:id>/', tests_soil_views.fraction_pass_save, name="fraction_pass_save"),
    path('fraction-retained/save/<int:id>/', tests_soil_views.fraction_retained_save, name="fraction_retained_save"),
    # Granulometric Global CRUD and PDF
    path('granulometric-global/', tests_soil_views.granulometric_global_list, name="granulometric_global_list"),
    path('granulometric-global/create/', tests_soil_views.granulometric_global_create, name="granulometric_global_create"),
    path('granulometric-global/<int:id>/update/', tests_soil_views.granulometric_global_update, name="granulometric_global_update"),
    path('granulometric-global/<int:id>/detail/', tests_soil_views.granulometric_global_detail, name="granulometric_global_detail"),
    path('granulometric-global/<int:id>/delete/', tests_soil_views.granulometric_global_delete, name="granulometric_global_delete"),
    path('granulometric-global/<int:id>/pdf/', tests_soil_views.granulometric_global_pdf, name="granulometric_global_pdf"),
        # Global Mesh CRUD
    path('global-mesh/save/<int:id>/', tests_soil_views.global_mesh_save, name="global_mesh_save"),
    # Sand Cone CRUD and PDF
    path('saned-cone/', tests_soil_views.sand_cone_list, name="sand_cone_list"),
    path('saned-cone/create/', tests_soil_views.sand_cone_create, name="sand_cone_create"),
    path('saned-cone/<int:id>/update/', tests_soil_views.sand_cone_update, name="sand_cone_update"),
    path('saned-cone/<int:id>/detail/', tests_soil_views.sand_cone_detail, name="sand_cone_detail"),
    path('saned-cone/<int:id>/delete/', tests_soil_views.sand_cone_delete, name="sand_cone_delete"),
    path('saned-cone/<int:id>/pdf/', tests_soil_views.sand_cone_pdf, name="sand_cone_pdf"),
        # humid-density, content-moisture, moisture-carbure, correction-sandcone  CRUD
    path('humid-density/save/<int:id>/', tests_soil_views.humid_density_save, name="humid_density_save"),
    path('content-moisture/save/<int:id>/', tests_soil_views.content_moisture_save, name="content_moisture_save"),
    path('correction-sandcone/save/<int:id>/', tests_soil_views.correction_sandcone_save, name="correction_sandcone_save"),
]

tests_soil/forms/equivalent.py
from django import forms
from functools import partial
from datetime import datetime
from django.forms import inlineformset_factory

from accounts.models import User
from tests_soil.models import Equivalent, Equiv
from construction.models import Construction
from reference_person.models import ReferencePerson
from course.models import Course

DateInput = partial(forms.DateInput, {"class": "datepicker"})

class EquivalentForm(forms.ModelForm):
    course = forms.ModelChoiceField(queryset=Course.objects.all(), label="Curso Especifico", required=True)

    class Meta:
        model = Equivalent
        fields = [
            'pit',
            'layer',
            'sampling_date',
            'done_date',
            'course'
        ]
        labels = {
            'pit': 'Calicata',
            'layer': 'Estrato',
            'sampling_date': 'Fecha de Extracción',
            'done_date': 'Fecha del Ensayo',
        }
        help_texts = {
            'pit': 'Nombre Propio de la Calicata',
        }
        widgets = {
            'sampling_date': DateInput(),
            'done_date': DateInput(), 
        }


class EquivalentFormClient(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.filter(is_client=True), label="Escoge el Cliente", required=True)

    class Meta:
        model = Equivalent
        fields = [
            'user',
            'pit',
            'layer',
            'sampling_date',
            'done_date',
            'reference_person',
            'construction',
        ]
        labels = {
            'pit': 'Calicata',
            'layer': 'Estrato',
            'sampling_date': 'Fecha de Extracción',
            'done_date': 'Fecha del Ensayo',
            'reference_person': 'Persona de Referencia',
            'construction': 'Construcción de Referencia',
        }
        help_texts = {
            'pit': 'Nombre Propio de la Calicata',
        }
        widgets = {
            'sampling_date': DateInput(),
            'done_date': DateInput(), 
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['reference_person'].queryset = ReferencePerson.objects.none()
        self.fields['reference_person'].required = True
        self.fields['construction'].queryset = Construction.objects.none()
        self.fields['construction'].required = True

        if 'user' in self.data:
            try:
                user_id = int(self.data.get('user'))
                self.fields['reference_person'].queryset = ReferencePerson.objects.filter(client_profile__user=user_id)
                self.fields['construction'].queryset = Construction.objects.filter(client_profile__user=user_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset

        elif self.instance.pk:
            self.fields['reference_person'].queryset = self.instance.user.clientprofile.referenceperson_set.all()
            self.fields['reference_person'].required = True
            self.fields['construction'].queryset = self.instance.user.clientprofile.construction_set.all()
            self.fields['construction'].required = True


class EquivForm(forms.ModelForm):

    class Meta:
        model = Equiv
        fields = [
            'max_size',
            'start_sat_time',
            'out_sat_time',
            'start_dec_time',
            'out_dec_time',
            'max_high_fine',
            'max_high_sand',
        ]
        labels = {
            'max_size': 'Tamaño Máximo',
            'start_sat_time': 'Hora de Entrada a Saturación',
            'out_sat_time': 'Hora de Salida de Saturación',
            'start_dec_time': 'Hora de Entrada a Decantación',
            'out_dec_time': 'Hora de Salida de Decantación',
            'max_high_fine': 'Altura Máxima del Material Fino',
            'max_high_sand': 'Altura Máxima de la Arena'
        }
        help_texts = {
            'max_size': 'Pasante del tamiz #4 <br> Aproximación (0.01 mm)',
            'start_sat_time': 'Unidades (hh:mm:ss)',
            'out_sat_time': 'Unidades (hh:mm:ss)',
            'start_dec_time': 'Unidades (hh:mm:ss)',
            'out_dec_time': 'Unidades (hh:mm:ss)',
            'max_high_fine': 'Unidades (mm) <br> Aproximación (0.1 mm)',
            'max_high_sand': 'Unidades (mm) <br> Aproximación (0.1 mm)',
        }

EquivFormSet = inlineformset_factory(Equivalent, Equiv, form=EquivForm, max_num=3)

tests_soil/views/general_tests_soil.py
from django.shortcuts import render

def tests_soil_info_view(request):
    context = {
        "title": "Mecánica de Suelos Información",
    }
    return render(request, 'tests_soil/info_tests_soil.html', context)


def tests_soil_equips_view(request):
    context = {
        "title": "Mecánica de Suelos Equipos",
    }
    return render(request, 'tests_soil/equips_tests_soil.html', context)


def tests_soil_guides_view(request):
    context = {
        "title": "Mecánica de Suelos Guias de los Ensayos",
    }
    return render(request, 'tests_soil/guides_tests_soil.html', context)


def tests_soil_teachers_view(request):
    context = {
        "title": "Mecánica de Suelos Plana Docente",
    }
    return render(request, 'tests_soil/teachers_tests_soil.html', context)

templates/tests_soil/base_sidenav_tests_soil.html
<div id="menu">
  <div class="list-group">
    <a href="#" class="list-group-item unique-color white-text" data-toggle="collapse" data-target="#list-one" data-parent="#menu"><i class="fas fa-laptop pr-2"></i>Mecánica de Suelos</a>
    <div class="list-group collapse" id="list-one">
      <a class="list-group-item" href="{% url 'tests_soil:info' %}"><i class="fas fa-angle-double-right pr-2"></i>Información General</a>
      <a class="list-group-item" href="{% url 'tests_soil:equips' %}"><i class="fas fa-angle-double-right pr-2"></i>Equipos Implementados</a>
      <a class="list-group-item" href="{% url 'tests_soil:guides' %}"><i class="fas fa-angle-double-right pr-2"></i>Guias de Ensayos</a>
      <a class="list-group-item" href="{% url 'tests_soil:teachers' %}"><i class="fas fa-angle-double-right pr-2"></i>Plana Docente</a>
    </div>
    <a href="#" class="list-group-item unique-color white-text" data-toggle="collapse" data-target="#list-two" data-parent="#menu"><i class="fas fa-vials  pr-2"></i>Ensayos</a>
    <div class="list-group collapse" id="list-two">
      <a class="list-group-item" href="{% url 'tests_soil:equivalent_list' %}" ><i class="fas fa-angle-double-right pr-2"></i>Determinación del Equivalente de Arena</a>
      <a class="list-group-item" href="{% url 'tests_soil:fine_material_list' %}" ><i class="fas fa-angle-double-right pr-2"></i>Material Más Fino Tamiz 75μm</a>
      <a class="list-group-item" href="{% url 'tests_soil:granulometric_global_list' %}" ><i class="fas fa-angle-double-right pr-2"></i>Clasificación de Suelos - Granulometría Global</a>
      <a class="list-group-item" href="{% url 'tests_soil:limit_list' %}" ><i class="fas fa-angle-double-right pr-2"></i>Límite Líquido y Límite Plástico</a>
      <a class="list-group-item" href="{% url 'tests_soil:moisture_content_list' %}" ><i class="fas fa-angle-double-right pr-2"></i>Contenido de Humedad de Suelos</a>
      <a class="list-group-item" href="{% url 'tests_soil:proctor_m_list' %}" ><i class="fas fa-angle-double-right pr-2"></i>Proctor Modificado MTC E115</a>
      <a class="list-group-item" href="{% url 'tests_soil:sand_cone_list' %}" ><i class="fas fa-angle-double-right pr-2"></i>Densidad Húmeda, Metodo Cono de Arena</a>
      <a class="list-group-item" href="{% url 'tests_soil:specific_gravity_list' %}" ><i class="fas fa-angle-double-right pr-2"></i>Gravedad Especifica de los Suelos (Picometro de Agua)</a>
    </div>
  </div>
</div>

templates/tests_soil/base_tests_soil.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body>

    {% include 'header.html' %}
    {% if request.user.username %}
        <p class="username">Welcome {{ request.user.username }}</p>
    {% endif %}

    <main role="main" class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} mt-3">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="my-5">
            <div class="row">
                <div class="col-md-3 col-lg-3">
                    {% include 'tests_soil/base_sidenav_tests_soil.html' %}
                </div>
                <div class="col-md-9 col-lg-9">
                    {% block soil %}
                    {% endblock %}
                </div>              
            </div>
        </div>
    </main>
          
    {% include 'footer.html' %}

    {% include 'scripts.html' %}

    {% block js %}
    {% endblock %}
   
</body>
</html>

templates/tests_soil/equips_tests_soil.html
{% extends 'tests_soil/base_tests_soil.html' %}

{% block soil %}
<section class="my-4">

  <!-- Section heading -->
  <h1 class="h1-responsive font-weight-bold text-center my-4">{{ title }}</h1>
  <!-- Section description -->
  <p class="text-center dark-grey-text w-responsive mx-auto ">Duis aute irure dolor in reprehenderit in
    voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <hr class="my-4">
  
  <!-- Grid row -->
  <div class="row my-4">

    <!-- Grid column -->
    <div class="col-lg-5 col-xl-4">

      <!-- Featured image -->
      <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
        <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Others/images/49.jpg" alt="Sample image">
        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-7 col-xl-8">

      <!-- Post title -->
      <h3 class="font-weight-bold mb-3"><strong>Maquina de Compresión</strong></h3>
      <!-- Excerpt -->
      <p class="dark-grey-text">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit
        quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus
        et aut officiis debitis cum soluta nobis est eligendi placeat facere aut rerum.</p>
      <!-- Post data -->
      <p>by <a class="font-weight-bold">Jessica Clark</a>, 19/04/2018</p>
      <!-- Read more button -->
      <a class="btn btn-primary btn-md"><i class="fas fa-file-download mr-2"></i>Read more</a>
  
    </div>
    <!-- Grid column -->
  </div>

  <hr class="my-4">
  <!-- Grid row --> 
  <div class="row my-4">

    <!-- Grid column -->
    <div class="col-lg-5 col-xl-4">

      <!-- Featured image -->
      <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
        <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Others/images/49.jpg" alt="Sample image">
        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-7 col-xl-8">

      <!-- Post title -->
      <h3 class="font-weight-bold mb-3"><strong>Herramientas Comunes</strong></h3>
      <!-- Excerpt -->
      <p class="dark-grey-text">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit
        quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus
        et aut officiis debitis cum soluta nobis est eligendi placeat facere aut rerum.</p>
      <ul class="dark-grey-text">
        <li>Lorem ipsum ess nobis, odio ab nemo facere!</li>
        <li>Odit autem nus voluptate hic!</li>
        <li>Alias qui, elendus exercitationem facere quo.</li>
        <li>Obcaecati il.</li>
        <li>Corrupti, quam rerum voluptatum sequi.</li>
        <li>Esse error aotam soluta?</li>
        <li>Perspiciatise! Beatae.</li>
        <li>Tenetur reicdolorem.</li>
        <li>Quidem nullaqui, perferendis quia.</li>
        <li>Quibusdam, snctio!</li>
      </ul>
      <!-- Post data -->
      <p>by <a class="font-weight-bold">Jessica Clark</a>, 19/04/2018</p>
      <!-- Read more button -->
      <a class="btn btn-primary btn-md"><i class="fas fa-file-download mr-2"></i>Read more</a>
  
    </div>
    <!-- Grid column -->
  </div>
  <!-- Grid row -->  
</section>

<hr class="my-4">
<!-- Section: Blog v.3 -->

{% endblock %}

templates/tests_soil/guides_tests_soil.html
{% extends 'tests_soil/base_tests_soil.html' %}

{% block soil %}
<section class="my-4">

  <!-- Section heading -->
  <h1 class="h1-responsive font-weight-bold text-center my-4">{{ title }}</h1>
  <!-- Section description -->
  <p class="text-center dark-grey-text w-responsive mx-auto ">Duis aute irure dolor in reprehenderit in
    voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <hr class="my-4">
  
  <!-- Grid row -->
  <div class="row my-4">

    <!-- Grid column -->
    <div class="col-lg-5 col-xl-4">

      <!-- Featured image -->
      <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
        <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Others/images/49.jpg" alt="Sample image">
        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-7 col-xl-8">

      <!-- Post title -->
      <h3 class="font-weight-bold mb-3"><strong>Ensayo de Compresión de Dados de Grout</strong></h3>
      <!-- Excerpt -->
      <p class="dark-grey-text">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit
        quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus
        et aut officiis debitis cum soluta nobis est eligendi placeat facere aut rerum.</p>
      <!-- Post data -->
      <p>by <a class="font-weight-bold">Jessica Clark</a>, 19/04/2018</p>
      <!-- Read more button -->
      <a class="btn btn-primary btn-md"><i class="fas fa-file-download mr-2"></i>Read more</a>
  
    </div>
    <!-- Grid column -->
  </div>

  <hr class="my-4">
  <!-- Grid row --> 
  <div class="row my-4">

    <!-- Grid column -->
    <div class="col-lg-5 col-xl-4">

      <!-- Featured image -->
      <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
        <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Others/images/49.jpg" alt="Sample image">
        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-7 col-xl-8">

      <!-- Post title -->
      <h3 class="font-weight-bold mb-3"><strong>Ensayo de Compresión de Testigos de Concreto</strong></h3>
      <!-- Excerpt -->
      <p class="dark-grey-text">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit
        quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus
        et aut officiis debitis cum soluta nobis est eligendi placeat facere aut rerum.</p>
      <!-- Post data -->
      <p>by <a class="font-weight-bold">Jessica Clark</a>, 19/04/2018</p>
      <!-- Read more button -->
      <a class="btn btn-primary btn-md"><i class="fas fa-file-download mr-2"></i>Read more</a>
  
    </div>
    <!-- Grid column -->
  </div>
  <!-- Grid row -->  
</section>

<hr class="my-4">
<!-- Section: Blog v.3 -->

{% endblock %}