labs/urls.py
from django.urls import path

from . import views as labs_views

app_name = "labs"

urlpatterns = [
    # Generals Views
    path('', labs_views.home_view, name="home"),
    path('intro/', labs_views.intro_view, name="intro"),
    path('pricing/', labs_views.pricing_view, name="pricing"),
    path('contact/', labs_views.contact_view, name="contact"),
    # Laboratories Views
    path('tests-concrete/', labs_views.labs_concrete_view, name="concrete"),
    path('tests-material/', labs_views.labs_material_view, name="material"),
    path('tests-soil/', labs_views.labs_soil_view, name="soil"),
    # Sectors Views
        # Client Sector 
    path('sectors-client/', labs_views.sector_client_view, name="client"),
    path('sectors-client-info/', labs_views.sector_client_info_view, name="client_info"),
    path('sectors-client-equips-concrete/', labs_views.client_equips_concrete_view, name="client_equips_concrete"),
    path('sectors-client-equips-material/', labs_views.client_equips_material_view, name="client_equips_material"),
    path('sectors-client-equips-soil/', labs_views.client_equips_soil_view, name="client_equips_soil"),
        # Bach Sector
    path('sectors-bach/', labs_views.sector_bach_view, name="bach"),
    path('sectors-bach-info/', labs_views.sector_bach_info_view, name="bach_info"),
    path('sectors-bach-equips-concrete/', labs_views.bach_equips_concrete_view, name="bach_equips_concrete"),
    path('sectors-bach-equips-material/', labs_views.bach_equips_material_view, name="bach_equips_material"),
    path('sectors-bach-equips-soil/', labs_views.bach_equips_soil_view, name="bach_equips_soil"),
        # Student Sector
    path('sectors-student/', labs_views.sector_student_view, name="student"),
    path('sectors-student-info/', labs_views.sector_student_info_view, name="student_info"),
    path('sectors-student-equips-concrete/', labs_views.student_equips_concrete_view, name="student_equips_concrete"),
    path('sectors-student-equips-material/', labs_views.student_equips_material_view, name="student_equips_material"),
    path('sectors-student-equips-soil/', labs_views.student_equips_soil_view, name="student_equips_soil"),
        # General Sector
            # Info
    path('general/', labs_views.general_view, name="general"),
    path('general-personal/', labs_views.general_personal_view, name="general_personal"),
    path('general-clients/', labs_views.general_clients_view, name="general_clients"),
    path('general-ref-per/', labs_views.general_ref_per_view, name="general_ref_per"),
    path('general-construction/', labs_views.general_construction_view, name="general_construction"),
    path('general-bach/', labs_views.general_bach_view, name="general_bach"),
    path('general-thesis/', labs_views.general_thesis_view, name="general_thesis"),
    path('general-student/', labs_views.general_student_view, name="general_student"),
    path('general-equips/', labs_views.general_equips_view, name="general_equips"),
            # Info Tests Concrete
    path('general-diamond-pice-break/', labs_views.general_diamond_pice_break, name="general_diamond_pice_break"),
    path('general-pice-break/', labs_views.general_pice_break, name="general_pice_break"),
    path('general-prism-break/', labs_views.general_prism_break, name="general_prism_break"),
            # Info Tests Material
    path('general-brick-type/', labs_views.general_brick_type, name="general_brick_type"),
    path('general-masonry-compression/', labs_views.general_masonry_compression, name="general_masonry_compression"),
    path('general-wood-compression/', labs_views.general_wood_compression, name="general_wood_compression"),
            # Info Tests Soil
    path('general-equivalent/', labs_views.general_equivalent, name="general_equivalent"),
    path('general-fine-material/', labs_views.general_fine_material, name="general_fine_material"),
    path('general-granulometric-global/', labs_views.general_granulometric_global, name="general_granulometric_global"),
    path('general-limit/', labs_views.general_limit, name="general_limit"),
    path('general-moisture-content/', labs_views.general_moisture_content, name="general_moisture_content"),
    path('general-proctor-m/', labs_views.general_proctor_m, name="general_proctor_m"),
    path('general-sand-cone/', labs_views.general_sand_cone, name="general_sand_cone"),
    path('general-specific_gravity/', labs_views.general_specific_gravity, name="general_specific_gravity"),
]

tests_material/urls.py
from django.urls import path

from . import views as tests_material_views

app_name = "tests_material"

urlpatterns = [
    # General views Concrete
    path('info/', tests_material_views.tests_material_info_view, name="info"),
    path('equips/', tests_material_views.tests_material_equips_view, name="equips"),
    path('guides/', tests_material_views.tests_material_guides_view, name="guides"),
    path('teachers/', tests_material_views.tests_material_teachers_view, name="teachers"),
    # Brick Type CRUD and PDF
    path('brick-type/', tests_material_views.brick_type_list, name="brick_type_list"),
    path('brick-type/create/', tests_material_views.brick_type_create, name="brick_type_create"),
    path('brick-type/<int:id>/update/', tests_material_views.brick_type_update, name="brick_type_update"),
    path('brick-type/<int:id>/detail/', tests_material_views.brick_type_detail, name="brick_type_detail"),
    path('brick-type/<int:id>/delete/', tests_material_views.brick_type_delete, name="brick_type_delete"),
    path('brick-type/<int:id>/pdf/', tests_material_views.brick_type_pdf, name="brick_type_pdf"),
        #  CRUD
    path('variation-dimensions/save/<int:id>/', tests_material_views.variation_dimensions_save , name="variation_dimensions_save"),
    path('warping/save/<int:id>/', tests_material_views.warping_save , name="warping_save"),
    path('density-voids/save/<int:id>/', tests_material_views.density_voids_save , name="density_voids_save"),
    path('suction/save/<int:id>/', tests_material_views.suction_save , name="suction_save"),
    path('abs-satu-coeff/save/<int:id>/', tests_material_views.abs_satu_coeff_save , name="abs_satu_coeff_save"),
    path('compretion-brick/save/<int:id>/', tests_material_views.compretion_brick_save , name="compretion_brick_save"),
    # Wood Compression CRUD and PDF
    path('wood-compression/', tests_material_views.wood_compression_list, name="wood_compression_list"),
    path('wood-compression/create/', tests_material_views.wood_compression_create, name="wood_compression_create"),
    path('wood-compression/<int:id>/update/', tests_material_views.wood_compression_update, name="wood_compression_update"),
    path('wood-compression/<int:id>/detail/', tests_material_views.wood_compression_detail, name="wood_compression_detail"),
    path('wood-compression/<int:id>/delete/', tests_material_views.wood_compression_delete, name="wood_compression_delete"),
    path('wood-compression/<int:id>/pdf/', tests_material_views.wood_compression_pdf, name="wood_compression_pdf"),
        #  CRUD
    path('parallel-perpendicular/save/<int:id>/', tests_material_views.parallel_perpendicular_save , name="parallel_perpendicular_save"),
    # Masonry Compression CRUD and PDF
    path('masonry-compression/', tests_material_views.masonry_compression_list, name="masonry_compression_list"),
    path('masonry-compression/create/', tests_material_views.masonry_compression_create, name="masonry_compression_create"),
    path('masonry-compression/<int:id>/update/', tests_material_views.masonry_compression_update, name="masonry_compression_update"),
    path('masonry-compression/<int:id>/detail/', tests_material_views.masonry_compression_detail, name="masonry_compression_detail"),
    path('masonry-compression/<int:id>/delete/', tests_material_views.masonry_compression_delete, name="masonry_compression_delete"),
    path('masonry-compression/<int:id>/pdf/', tests_material_views.masonry_compression_pdf, name="masonry_compression_pdf"),
        #  CRUD
    path('masonry/save/<int:id>/', tests_material_views.masonry_save , name="masonry_save"),
]

tests_material/models/brick_type.py
from django.db import models
import datetime
import math
import numpy as np

from accounts.models import User
from equipments.models import Equip
from tools.models import Tool
from reference_person.models import ReferencePerson
from construction.models import Construction
from course.models import Course

class BrickType(models.Model):
    user            = models.ForeignKey(User, on_delete=models.CASCADE)
    name            = models.CharField(max_length=50, default="Tipo Ladrillo")
    name_element    = models.CharField(max_length=50, null=True, blank=True)
    brick_company   = models.CharField(max_length=100, null=True, blank=True)
    n_d_length      = models.FloatField()
    n_d_width       = models.FloatField()
    n_d_high        = models.FloatField()
    code            = models.CharField(max_length=255, unique=True, editable=False)
    sampling_date   = models.DateField()
    done_date       = models.DateField(default=datetime.datetime.now)
    dilate          = models.IntegerField(editable=False)
    created         = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)
    equipment           = models.ManyToManyField(Equip)
    tool                = models.ManyToManyField(Tool)    
    course              = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True, blank=True)
    reference_person    = models.ForeignKey(ReferencePerson, on_delete=models.SET_NULL, null=True, blank=True)
    construction        = models.ForeignKey(Construction, on_delete=models.SET_NULL, null=True, blank=True)

    def save(self, *args, **kwargs):

        # Generate the code for the barcode (e.g. RDC2009092701)
        date = datetime.datetime.today()
        letters = ""
        words = self.name.split()
        for word in words:
            letters += word[0]
        self.code = f"{letters.upper()}{date.year}{date.month}{date.day}{date.hour}{date.minute}{date.second}"

        # Generate the duration from the poured_data
        diff = self.done_date - self.sampling_date
        self.dilate = diff.days

        super(BrickType, self).save(*args, **kwargs)

    def __str__(self):
        return f"Tipo Ladrillo {self.id}"


class VariationDimensions(models.Model):
    name_element    = models.CharField(max_length=50)
    upface_length   = models.FloatField()
    downface_length = models.FloatField()
    average_length  = models.FloatField(editable=False)
    upface_width    = models.FloatField()
    downface_width  = models.FloatField()
    average_width   = models.FloatField(editable=False)
    high_backside   = models.FloatField()
    high_rightside  = models.FloatField()
    high_frontside  = models.FloatField()
    high_lefside    = models.FloatField()
    average_high    = models.FloatField(editable=False)
    brick_type  = models.ForeignKey(BrickType, on_delete=models.CASCADE)
    equipment   = models.ManyToManyField(Equip)
    tool        = models.ManyToManyField(Tool)    

    def save(self, *args, **kwargs):

        # Generate average_length
        al = (self.upface_length + self.downface_length) / 2
        self.average_length = round(al, 1)

        # Generate average_width
        aw = (self.upface_width + self.downface_width) / 2
        self.average_width = round(aw, 1)

        # Generate average_high
        ah = (self.high_backside + self.high_rightside + self.high_frontside + self.high_lefside) / 4
        self.average_high = round(ah, 1)

        super(VariationDimensions, self).save(*args, **kwargs)

    def __str__(self):
        return f"Variacion Dimensiones Ladrillo {self.id}"


class Warping(models.Model):
    name_element    = models.CharField(max_length=50)
    upface_concave      = models.FloatField(default=0)
    upface_convex       = models.FloatField(default=0)
    downface_concave    = models.FloatField(default=0)
    downface_convex     = models.FloatField(default=0)
    brick_type  = models.ForeignKey(BrickType, on_delete=models.CASCADE)
    equipment   = models.ManyToManyField(Equip)
    tool        = models.ManyToManyField(Tool)    

    def __str__(self):
        return f"Alabeo Ladrillo {self.id}"


class DensityVoids(models.Model):
    name_element    = models.CharField(max_length=50)
    length          = models.FloatField()
    width           = models.FloatField()
    high            = models.FloatField()
    volume_brick    = models.FloatField(editable=False)
    sc              = models.FloatField()
    su              = models.FloatField()
    volume_void     = models.FloatField(editable=False)
    volume_real     = models.FloatField(editable=False)
    void_percentage = models.FloatField(editable=False)
    weight          = models.FloatField()
    density         = models.FloatField(editable=False)
    brick_type  = models.ForeignKey(BrickType, on_delete=models.CASCADE)
    equipment   = models.ManyToManyField(Equip)
    tool        = models.ManyToManyField(Tool)    

    def save(self, *args, **kwargs):

        # Generate volume_brick
        volume = (self.length*0.1) * (self.width*0.1) * (self.high*0.1)
        self.volume_brick = round(volume, 1)

        # Generate volume_void
        vv = self.su / self.sc 
        self.volume_void = round(vv, 1)

        # Generate volume_real
        vr = self.volume_brick - self.volume_void
        self.volume_real = round(vr, 1)

        # Generate void_percentage
        vp = (self.volume_void / self.volume_brick) *  100
        self.void_percentage = round(vp, 0)

        # Generate density
        d = self.weight / self.volume_real
        self.density = round(d, 2)

        super(DensityVoids, self).save(*args, **kwargs)

    def __str__(self):
        return f"Densidad y Vacíos {self.id}"


class Suction(models.Model):
    name_element    = models.CharField(max_length=50)
    nomal_weight    = models.FloatField()
    dry_weight      = models.FloatField()
    diff_weight     = models.FloatField(editable=False)
    length          = models.FloatField()
    width           = models.FloatField()
    face_area       = models.FloatField(editable=False)
    face_wet_weight = models.FloatField()
    face_wet_weight_correction = models.FloatField(editable=False)
    brick_type  = models.ForeignKey(BrickType, on_delete=models.CASCADE)
    equipment   = models.ManyToManyField(Equip)
    tool        = models.ManyToManyField(Tool)    

    def save(self, *args, **kwargs):

        # Generate diff_weight
        dw = self.nomal_weight - self.dry_weight
        self.diff_weight = round(dw, 1)

        # Generate face_area
        fa = (self.length*0.1) * (self.width*0.1)
        self.face_area = round(fa, 1)

        # Generate face_wet_weight_correction
        fwwc = ((self.face_wet_weight - self.dry_weight) / self.face_area) * 200
        self.face_wet_weight_correction = round(fwwc, 1)

        super(Suction, self).save(*args, **kwargs)

    def __str__(self):
        return f"Succion Ladrillo {self.id}"


class AbsSatuCoeff(models.Model):
    name_element    = models.CharField(max_length=50)
    dry_weight          = models.FloatField()
    wet_weight_cool_24  = models.FloatField()
    wet_weight_hot_5    = models.FloatField()
    abs_brick           = models.FloatField(editable=False)
    abs_max_brick       = models.FloatField(editable=False)
    coeff_sat           = models.FloatField(editable=False)
    brick_type  = models.ForeignKey(BrickType, on_delete=models.CASCADE)
    equipment   = models.ManyToManyField(Equip)
    tool        = models.ManyToManyField(Tool)    

    def save(self, *args, **kwargs):

        # Generate abs_brick
        ab = 100 * (self.wet_weight_cool_24 - self.dry_weight) / self.dry_weight
        self.abs_brick = round(ab, 1)

        # Generate abs_max_brick
        amb = 100 * (self.wet_weight_hot_5 - self.dry_weight) / self.dry_weight
        self.abs_max_brick = round(amb, 1)
        
        # Generate coeff_sat
        cs = (self.wet_weight_cool_24 - self.dry_weight) / (self.wet_weight_hot_5 - self.dry_weight)
        self.coeff_sat = round(cs, 2)

        super(AbsSatuCoeff, self).save(*args, **kwargs)

    def __str__(self):
        return f"Absorción Coeficiente Saturacion Ladrillo {self.id}"


class CompretionBrick(models.Model):
    name_element    = models.CharField(max_length=50)
    upface_length   = models.FloatField()
    upface_width    = models.FloatField()
    downface_length = models.FloatField()
    downface_width  = models.FloatField()
    upface_area     = models.FloatField(editable=False)
    downface_area   = models.FloatField(editable=False)
    average_area    = models.FloatField(editable=False)
    load            = models.FloatField()
    fc              = models.FloatField(editable=False)
    fc_MPa          = models.FloatField(editable=False)
    brick_type  = models.ForeignKey(BrickType, on_delete=models.CASCADE)
    equipment   = models.ManyToManyField(Equip)
    tool        = models.ManyToManyField(Tool)    

    def save(self, *args, **kwargs):

        # Generate upface_area
        afa = (self.upface_length*0.1) * (self.upface_width*0.1) 
        self.upface_area = round(afa, 1)

        # Generate downface_area
        dfa = (self.downface_length*0.1) * (self.downface_width*0.1) 
        self.downface_area = round(dfa, 1)
        
        # Generate average_area
        aa = (self.upface_area + self.downface_area) / 2
        self.average_area = round(aa, 1)

        # Generate compression_resistance
        fc = self.load / self.average_area
        self.fc = round(fc, 2)

        # Generate fc_MPa
        fc_MPa = self.fc*0.0981 
        self.fc_MPa = round(fc_MPa, 1)

        super(CompretionBrick, self).save(*args, **kwargs)

    def __str__(self):
        return f"Compresion Ladrillo {self.id}"

templates/tests_material/brick_type/abs_satu_coeff_form.html
{% extends 'tests_material/base_tests_material.html' %}
{% load crispy_forms_tags %}

{% block material %}
<div class="row">
    <div class="col-sm-9 col-lg-12 mx-auto my-3">
        <div class="card shadow">
            <div class="card-body">
                <h4 class="h4-responsive font-weight-bold text-center ">{{ title }}</h4>
                <hr class="my-3">
                <span class="table-add float-right">
                    <a href="{% url 'tests_material:brick_type_list' %}" class="text-primary">
                        <i class="fas fa-times fa-1x" aria-hidden="true"></i>
                    </a>
                </span>

                <form 
                    action="{% url 'tests_material:abs_satu_coeff_save' obj.id %}" 
                    method="POST">
                    <div>
                        <div class="row">
                        {% csrf_token %}
                        {{ formset.management_form }}
                        {% for form in formset %}
                            <div class="col-md-6 col-lg-4">
                                <h6 class="h6-responsive font-weight-bold text-left ">Ensayo {{ forloop.counter }}</h6>
                                {{ form|crispy }}
                                <hr class="my-3">
                            </div>
                            {% endfor %}
                        </div>
                        <div class="mt-5">
                            <button class="btn btn-primary btn-block" name="submit" type="submit">Crear o Editar Ensayos</button>
                            <a href="{% url 'tests_material:brick_type_list' %}" class="btn btn-primary btn-block" type="button">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/tests_material/brick_type/brick_type_form.html
{% extends 'tests_material/base_tests_material.html' %}
{% load crispy_forms_tags %}

{% block material %}
<div class="row">
    <div class="col-md-6 mx-auto my-3">
        <div class="card shadow">
            <div class="card-body">
                <h4 class="h4-responsive font-weight-bold text-center ">{{ title }}</h4>
                <hr class="my-3">

                <span class="table-add float-right">
                    <a href="{% url 'tests_material:brick_type_list' %}" class="text-primary">
                        <i class="fas fa-times fa-1x" aria-hidden="true"></i>
                    </a>
                </span>
                {% if obj %}
                <form 
                    id="brickTypeForm" 
                    data-ref-per-url="{% url 'reference_person:ajax_reference_person' %}" 
                    data-const-url="{% url 'construction:ajax_construction' %}"
                    action="{% url 'tests_material:brick_type_update' obj.id %}" 
                    method="POST">
                {% else %}
                <form 
                    id="brickTypeForm" 
                    data-ref-per-url="{% url 'reference_person:ajax_reference_person' %}" 
                    data-const-url="{% url 'construction:ajax_construction' %}"
                    action="{% url 'tests_material:brick_type_create' %}" 
                    method="POST">
                {% endif %}
                    <div>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="mt-5">
                            {% if obj %}
                            <button class="btn btn-primary btn-block" name="submit" type="submit">Editar Ensayo</button>
                            {% else %}
                            <button class="btn btn-primary btn-block" name="submit" type="submit">Crear Ensayo y Sigiente Paso</button>
                            {% endif %}
                            <a href="{% url 'tests_material:brick_type_list' %}" class="btn btn-primary btn-block" type="button">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    $( function() {
      $( ".datepicker" ).datepicker();
    } );
</script>
<script>
    $("#id_user").change(function () {
    
      var url = $("#brickTypeForm").attr("data-ref-per-url");  // get the url of the `load_cities` view
      var userId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'user': userId       // add the country id to the GET parameters
        },

        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_reference_person").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });
    });
</script>  
<script>
    $("#id_user").change(function () {
    
      var url = $("#brickTypeForm").attr("data-const-url");  // get the url of the `load_cities` view
      var userId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'user': userId       // add the country id to the GET parameters
        },

        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_construction").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });
    });
</script>  
{% endblock %}

templates/tests_material/brick_type/brick_type_list.html
{% extends 'tests_material/base_tests_material.html' %}

{% block material %}
<!-- Section: Blog v.3 -->
<section class="my-3">

    <!-- Section heading -->
    <h2 class="h2-responsive font-weight-bold text-center my-4">{{ title }}</h2>
    <!-- Section description -->
    <p class="text-center dark-grey-text w-responsive mx-auto mb-5">Duis aute irure dolor in reprehenderit in
      voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    
    <!-- Grid row -->
    <div class="row">
    
        <!-- Grid column -->
        <div class="col-lg-5 col-xl-4">
        
          <!-- Featured image -->
          <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
            <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Others/images/49.jpg" alt="Sample image">
            <a>
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
        
        </div>
        <!-- Grid column -->
      
        <!-- Grid column -->
        <div class="col-lg-7 col-xl-8">
        
          <!-- Post title -->
          <h3 class="font-weight-bold mb-3"><strong>Descripción</strong></h3>
          <!-- Excerpt -->
          <p class="dark-grey-text">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit
            quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus
            et aut officiis debitis cum soluta nobis est eligendi placeat facere aut rerum.</p>
          <!-- Post data -->
          <p>by <a class="font-weight-bold">Jessica Clark</a>, 19/04/2018</p>
          <!-- Read more button -->
          <a data-toggle="tooltip" title="Descargar PDF" role="button" class="btn btn-primary btn-md"><i class="fas fa-file-download mr-2"></i>Manual</a>
        </div>
        <!-- Grid column -->  
    </div>
    <!-- Grid row -->
</section>
<!-- Section: Blog v.3 -->

<hr class="my-5">

<section class="my-3">
    <!-- Editable table -->
    <div class="card">
      <h4 class="h4-responsive card-header text-center font-weight-bold text-uppercase py-4">{{ title }}</h4>
      <div class="card-body">
        <div>
          {% if request.user.is_superuser or request.user.is_group or request.user.is_bach or request.user.is_admin %}
          <span class="table-add float-right mb-3 mr-2">
            <a href="{% url 'tests_material:brick_type_create' %}" class="text-primary">
              <i class="fas fa-plus fa-2x" aria-hidden="true"></i>
            </a>
          </span>
          {% endif %}
          <table id="brickType" class="display compact table table-bordered table-responsive table-striped text-center">
            <thead class="primary-color-dark white-text">
              <tr>
                <th rowspan="2">Usuario</th>
                <th rowspan="2">Id</th>
                <th colspan="3">Item</th>
                <th colspan="2">Fecha</th>
                <th rowspan="2">Tiempo de Espera (días)</th>
                <th rowspan="2">Acciones</th>
              </tr>
              <tr>
                <th>Elemento</th>
                <th>Ladrillera</th>
                <th>Código</th>
                <th>Muestreo</th>
                <th>Ensayo</th>
              </tr>
            </thead>
            <tbody>
              {% for obj in obj_list %}
              <tr>
                <td>{{ obj.user.username }}</td>
                <td>{{ obj.id }}</td>
                <td>{{ obj.name_element }}</td>
                <td>{{ obj.brick_company }}</td>
                <td>{{ obj.code }}</td>
                <td>{{ obj.sampling_date|date:"d/m/Y" }}</td>
                <td>{{ obj.done_date|date:"d/m/Y" }}</td>
                <td>{{ obj.dilate }}</td>
                <td>
                  {% if user.is_authenticated %}
                  <div class="btn-group" role="group" aria-label="Basic example">
                    <a
                    href="{% url 'tests_material:brick_type_detail' obj.id %}"
                    data-toggle="tooltip" title="Detalles" role="button" class="btn btn-primary btn-sm px-2 mx-1"><i class="far fa-eye"></i>
                  </a>
                    {% if user.is_superuser or user.is_group or user.is_bach or user.is_admin %}
                    <a
                      href="{% url 'tests_material:variation_dimensions_save' obj.id %}"
                      data-toggle="tooltip" title="Editar o Crear Variación de Dimensiones" role="button" class="btn btn-dark btn-sm px-2 mx-1"><i class="fas fa-plus"></i>
                    </a>
                    <a
                      href="{% url 'tests_material:warping_save' obj.id %}"
                      data-toggle="tooltip" title="Editar o Crear Alabeo" role="button" class="btn btn-dark btn-sm px-2 mx-1"><i class="fas fa-plus"></i>
                    </a>
                    <a
                      href="{% url 'tests_material:density_voids_save' obj.id %}"
                      data-toggle="tooltip" title="Editar o Crear Densidad y % de Vacíos" role="button" class="btn btn-dark btn-sm px-2 mx-1"><i class="fas fa-plus"></i>
                    </a>
                    <a
                      href="{% url 'tests_material:suction_save' obj.id %}"
                      data-toggle="tooltip" title="Editar o Crear Succión" role="button" class="btn btn-dark btn-sm px-2 mx-1"><i class="fas fa-plus"></i>
                    </a>
                    <a
                      href="{% url 'tests_material:abs_satu_coeff_save' obj.id %}"
                      data-toggle="tooltip" title="Editar o Crear % Absorción y Coeficiente de Saturación" role="button" class="btn btn-dark btn-sm px-2 mx-1"><i class="fas fa-plus"></i>
                    </a>
                    <a
                      href="{% url 'tests_material:compretion_brick_save' obj.id %}"
                      data-toggle="tooltip" title="Editar o Crear Compresión de Ladrillos" role="button" class="btn btn-dark btn-sm px-2 mx-1"><i class="fas fa-plus"></i>
                    </a>
                    <a 
                      href="{% url 'tests_material:brick_type_update' obj.id %}" 
                      data-toggle="tooltip" title="Editar" role="button" class="btn btn-success btn-sm px-2 mx-1"><i class="fas fa-edit"></i>
                    </a>
                    <a 
                      href="{% url 'tests_material:brick_type_delete' obj.id %}"
                      data-toggle="tooltip" title="Borrar" role="button" class="btn btn-danger btn-sm px-2 mx-1"><i class="fas fa-trash"></i>
                    </a>
                    <a 
                      href="{% url 'tests_material:brick_type_pdf' obj.id %}" 
                      data-toggle="tooltip" title="Descargar PDF" role="button" class="btn btn-orange btn-sm px-2 mx-1"><i class="far fa-file-pdf"></i>
                    </a>
                    {% endif %}
                  </div>
                  {% endif %}                  
                </td>
              </tr>
              {% endfor %}
              <!-- This is our clonable table line -->
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- Editable table -->
</section>

{% endblock %}
{% block js %}
<script>
  $(document).ready( function () {
    $('#brickType').DataTable({
      "scrollX": true,
      dom: 'B<"clear">lfrtip',
      buttons: [
          'csv', 'excel',
          {
            extend: 'pdfHtml5',
            orientation: 'landscape',
            pageSize: 'LEGAL',
            filename: '{{ file_name }}_{{ user.username }}_{{ obj_list.count }}'
          }
      ]
    });
  } );
</script>
{% endblock %}