construction/urls.py
from django.urls import path

from . import views as construction_views

app_name = "construction"

urlpatterns = [
    path('construction-create/', construction_views.construction_create, name="construction_create"),
    path('construction-update/<int:id>/', construction_views.construction_update, name="construction_update"),
    path('construction-delete/<int:id>/', construction_views.construction_delete, name="construction_delete"),
    # Ajax request Jquery
    path('ajax/construction/', construction_views.load_construction, name='ajax_construction'),
]

labs/urls.py
from django.urls import path

from . import views as labs_views

app_name = "labs"

urlpatterns = [
    # Generals Views
    path('', labs_views.home_view, name="home"),
    path('intro/', labs_views.intro_view, name="intro"),
    path('pricing/', labs_views.pricing_view, name="pricing"),
    path('contact/', labs_views.contact_view, name="contact"),
    # Laboratories Views
    path('tests-concrete/', labs_views.labs_concrete_view, name="concrete"),
    path('tests-material/', labs_views.labs_material_view, name="material"),
    path('tests-soil/', labs_views.labs_soil_view, name="soil"),
    # Sectors Views
        # Client Sector 
    path('sectors-client/', labs_views.sector_client_view, name="client"),
    path('sectors-client-info/', labs_views.sector_client_info_view, name="client_info"),
    path('sectors-client-equips-concrete/', labs_views.client_equips_concrete_view, name="client_equips_concrete"),
    path('sectors-client-equips-material/', labs_views.client_equips_material_view, name="client_equips_material"),
    path('sectors-client-equips-soil/', labs_views.client_equips_soil_view, name="client_equips_soil"),
        # Bach Sector
    path('sectors-bach/', labs_views.sector_bach_view, name="bach"),
    path('sectors-bach-info/', labs_views.sector_bach_info_view, name="bach_info"),
    path('sectors-bach-equips-concrete/', labs_views.bach_equips_concrete_view, name="bach_equips_concrete"),
    path('sectors-bach-equips-material/', labs_views.bach_equips_material_view, name="bach_equips_material"),
    path('sectors-bach-equips-soil/', labs_views.bach_equips_soil_view, name="bach_equips_soil"),
        # Student Sector
    path('sectors-student/', labs_views.sector_student_view, name="student"),
    path('sectors-student-info/', labs_views.sector_student_info_view, name="student_info"),
    path('sectors-student-equips-concrete/', labs_views.student_equips_concrete_view, name="student_equips_concrete"),
    path('sectors-student-equips-material/', labs_views.student_equips_material_view, name="student_equips_material"),
    path('sectors-student-equips-soil/', labs_views.student_equips_soil_view, name="student_equips_soil"),
        # General Sector
            # Info
    path('general/', labs_views.general_view, name="general"),
    path('general-personal/', labs_views.general_personal_view, name="general_personal"),
    path('general-clients/', labs_views.general_clients_view, name="general_clients"),
    path('general-ref-per/', labs_views.general_ref_per_view, name="general_ref_per"),
    path('general-construction/', labs_views.general_construction_view, name="general_construction"),
    path('general-bach/', labs_views.general_bach_view, name="general_bach"),
    path('general-thesis/', labs_views.general_thesis_view, name="general_thesis"),
    path('general-student/', labs_views.general_student_view, name="general_student"),
    path('general-equips/', labs_views.general_equips_view, name="general_equips"),
            # Info Tests Concrete
    path('general-diamond-pice-break/', labs_views.general_diamond_pice_break, name="general_diamond_pice_break"),
    path('general-pice-break/', labs_views.general_pice_break, name="general_pice_break"),
    path('general-prism-break/', labs_views.general_prism_break, name="general_prism_break"),
            # Info Tests Material
    path('general-brick-type/', labs_views.general_brick_type, name="general_brick_type"),
    path('general-masonry-compression/', labs_views.general_masonry_compression, name="general_masonry_compression"),
    path('general-wood-compression/', labs_views.general_wood_compression, name="general_wood_compression"),
            # Info Tests Soil
    path('general-equivalent/', labs_views.general_equivalent, name="general_equivalent"),
    path('general-fine-material/', labs_views.general_fine_material, name="general_fine_material"),
    path('general-granulometric-global/', labs_views.general_granulometric_global, name="general_granulometric_global"),
    path('general-limit/', labs_views.general_limit, name="general_limit"),
    path('general-moisture-content/', labs_views.general_moisture_content, name="general_moisture_content"),
    path('general-proctor-m/', labs_views.general_proctor_m, name="general_proctor_m"),
    path('general-sand-cone/', labs_views.general_sand_cone, name="general_sand_cone"),
    path('general-specific_gravity/', labs_views.general_specific_gravity, name="general_specific_gravity"),
]

reference_person/urls.py
from django.urls import path

from . import views as reference_person_views

app_name = "reference_person"

urlpatterns = [
    path('reference-person-create/', reference_person_views.reference_person_create, name="reference_person_create"),
    path('reference-person-update/<int:id>/', reference_person_views.reference_person_update, name="reference_person_update"),
    path('reference-person-delete/<int:id>/', reference_person_views.reference_person_delete, name="reference_person_delete"),
    # Ajax request Jquery
    path('ajax/reference_person/', reference_person_views.load_reference_person , name='ajax_reference_person'),
]

tests_soil/urls.py
from django.urls import path

from . import views as tests_soil_views

app_name = "tests_soil"

urlpatterns = [
    # General views Concrete
    path('info/', tests_soil_views.tests_soil_info_view, name="info"),
    path('equips/', tests_soil_views.tests_soil_equips_view, name="equips"),
    path('guides/', tests_soil_views.tests_soil_guides_view, name="guides"),
    path('teachers/', tests_soil_views.tests_soil_teachers_view, name="teachers"),
    # Limit CRUD and PDF
    path('limit/', tests_soil_views.limit_list, name="limit_list"),
    path('limit/create/', tests_soil_views.limit_create, name="limit_create"),
    path('limit/<int:id>/update/', tests_soil_views.limit_update, name="limit_update"),
    path('limit/<int:id>/detail/', tests_soil_views.limit_detail, name="limit_detail"),
    path('limit/<int:id>/delete/', tests_soil_views.limit_delete, name="limit_delete"),
    path('limit/<int:id>/pdf/', tests_soil_views.limit_pdf, name="limit_pdf"),
        # Liquid and Plastic CRUD
    path('liquid/save/<int:id>/', tests_soil_views.liquid_save, name="liquid_save"),
    path('plastic/save/<int:id>/', tests_soil_views.plastic_save, name="plastic_save"),
    # Fine Material CRUD and PDF
    path('fine-material/', tests_soil_views.fine_material_list, name="fine_material_list"),
    path('fine-material/create/', tests_soil_views.fine_material_create, name="fine_material_create"),
    path('fine-material/<int:id>/update/', tests_soil_views.fine_material_update, name="fine_material_update"),
    path('fine-material/<int:id>/detail/', tests_soil_views.fine_material_detail, name="fine_material_detail"),
    path('fine-material/<int:id>/delete/', tests_soil_views.fine_material_delete, name="fine_material_delete"),
    path('fine-material/<int:id>/pdf/', tests_soil_views.fine_material_pdf, name="fine_material_pdf"),
    # Equivalent CRUD and PDF
    path('equivalent/', tests_soil_views.equivalent_list, name="equivalent_list"),
    path('equivalent/create/', tests_soil_views.equivalent_create, name="equivalent_create"),
    path('equivalent/<int:id>/update/', tests_soil_views.equivalent_update, name="equivalent_update"),
    path('equivalent/<int:id>/detail/', tests_soil_views.equivalent_detail, name="equivalent_detail"),
    path('equivalent/<int:id>/delete/', tests_soil_views.equivalent_delete, name="equivalent_delete"),
    path('equivalent/<int:id>/pdf/', tests_soil_views.equivalent_pdf, name="equivalent_pdf"),
        # Equiv CRUD
    path('equiv/save/<int:id>/', tests_soil_views.equiv_save, name="equiv_save"),
    # Proctor M CRUD and PDF
    path('proctor-m/', tests_soil_views.proctor_m_list, name="proctor_m_list"),
    path('proctor-m/create/', tests_soil_views.proctor_m_create, name="proctor_m_create"),
    path('proctor-m/<int:id>/update/', tests_soil_views.proctor_m_update, name="proctor_m_update"),
    path('proctor-m/<int:id>/detail/', tests_soil_views.proctor_m_detail, name="proctor_m_detail"),
    path('proctor-m/<int:id>/delete/', tests_soil_views.proctor_m_delete, name="proctor_m_delete"),
    path('proctor-m/<int:id>/pdf/', tests_soil_views.proctor_m_pdf, name="proctor_m_pdf"),
        # Density CRUD
    path('density/save/<int:id>/', tests_soil_views.density_save, name="density_save"),
    # path('saturation/save/<int:id>/', tests_soil_views.saturation_save, name="saturation_save"),
    path('correction/save/<int:id>/', tests_soil_views.correction_save, name="correction_save"),
    # Moisture Content CRUD and PDF
    path('moisture-content/', tests_soil_views.moisture_content_list, name="moisture_content_list"),
    path('moisture-content/create/', tests_soil_views.moisture_content_create, name="moisture_content_create"),
    path('moisture-content/<int:id>/update/', tests_soil_views.moisture_content_update, name="moisture_content_update"),
    path('moisture-content/<int:id>/detail/', tests_soil_views.moisture_content_detail, name="moisture_content_detail"),
    path('moisture-content/<int:id>/delete/', tests_soil_views.moisture_content_delete, name="moisture_content_delete"),
    path('moisture-content/<int:id>/pdf/', tests_soil_views.moisture_content_pdf, name="moisture_content_pdf"),
        # Moisture Material CRUD
    path('moisture-material/save/<int:id>/', tests_soil_views.moisture_material_save, name="moisture_material_save"),
    # Specific Gravity CRUD and PDF
    path('specific-gravity/', tests_soil_views.specific_gravity_list, name="specific_gravity_list"),
    path('specific-gravity/create/', tests_soil_views.specific_gravity_create, name="specific_gravity_create"),
    path('specific-gravity/<int:id>/update/', tests_soil_views.specific_gravity_update, name="specific_gravity_update"),
    path('specific-gravity/<int:id>/detail/', tests_soil_views.specific_gravity_detail, name="specific_gravity_detail"),
    path('specific-gravity/<int:id>/delete/', tests_soil_views.specific_gravity_delete, name="specific_gravity_delete"),
    path('specific-gravity/<int:id>/pdf/', tests_soil_views.specific_gravity_pdf, name="specific_gravity_pdf"),
        # Fraction Pass and Retained CRUD
    path('fraction-pass/save/<int:id>/', tests_soil_views.fraction_pass_save, name="fraction_pass_save"),
    path('fraction-retained/save/<int:id>/', tests_soil_views.fraction_retained_save, name="fraction_retained_save"),
    # Granulometric Global CRUD and PDF
    path('granulometric-global/', tests_soil_views.granulometric_global_list, name="granulometric_global_list"),
    path('granulometric-global/create/', tests_soil_views.granulometric_global_create, name="granulometric_global_create"),
    path('granulometric-global/<int:id>/update/', tests_soil_views.granulometric_global_update, name="granulometric_global_update"),
    path('granulometric-global/<int:id>/detail/', tests_soil_views.granulometric_global_detail, name="granulometric_global_detail"),
    path('granulometric-global/<int:id>/delete/', tests_soil_views.granulometric_global_delete, name="granulometric_global_delete"),
    path('granulometric-global/<int:id>/pdf/', tests_soil_views.granulometric_global_pdf, name="granulometric_global_pdf"),
        # Global Mesh CRUD
    path('global-mesh/save/<int:id>/', tests_soil_views.global_mesh_save, name="global_mesh_save"),
    # Sand Cone CRUD and PDF
    path('saned-cone/', tests_soil_views.sand_cone_list, name="sand_cone_list"),
    path('saned-cone/create/', tests_soil_views.sand_cone_create, name="sand_cone_create"),
    path('saned-cone/<int:id>/update/', tests_soil_views.sand_cone_update, name="sand_cone_update"),
    path('saned-cone/<int:id>/detail/', tests_soil_views.sand_cone_detail, name="sand_cone_detail"),
    path('saned-cone/<int:id>/delete/', tests_soil_views.sand_cone_delete, name="sand_cone_delete"),
    path('saned-cone/<int:id>/pdf/', tests_soil_views.sand_cone_pdf, name="sand_cone_pdf"),
        # humid-density, content-moisture, moisture-carbure, correction-sandcone  CRUD
    path('humid-density/save/<int:id>/', tests_soil_views.humid_density_save, name="humid_density_save"),
    path('content-moisture/save/<int:id>/', tests_soil_views.content_moisture_save, name="content_moisture_save"),
    path('correction-sandcone/save/<int:id>/', tests_soil_views.correction_sandcone_save, name="correction_sandcone_save"),
]

tests_soil/models/equivalent.py
from django.db import models
import datetime
import math
import numpy as np

from accounts.models import User
from equipments.models import Equip
from tools.models import Tool
from reference_person.models import ReferencePerson
from construction.models import Construction
from course.models import Course

class Equivalent(models.Model):
    LAYER_CHOICES = (
        ("UNO", "Estrato 1"),
        ("DOS", "Estrato 2"),
        ("TRES", "Estrato 3"),
        ("CUATRO", "Estrato 4"),
    )
    user            = models.ForeignKey(User, on_delete=models.CASCADE)
    name            = models.CharField(max_length=50, default="Valor Equivalente Arena Finos")
    pit             = models.CharField(max_length=50, null=True, blank=True)
    layer           = models.CharField(choices=LAYER_CHOICES, max_length=6)
    code            = models.CharField(max_length=255, unique=True, editable=False)
    sampling_date   = models.DateField()
    done_date       = models.DateField(default=datetime.datetime.now)
    dilate          = models.IntegerField(editable=False)
    created         = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)
    equipment           = models.ManyToManyField(Equip)
    tool                = models.ManyToManyField(Tool)    
    course              = models.ForeignKey(Course, models.SET_NULL, null=True, blank=True)
    reference_person    = models.ForeignKey(ReferencePerson, models.SET_NULL, null=True, blank=True)
    construction        = models.ForeignKey(Construction, models.SET_NULL, null=True, blank=True)

    def save(self, *args, **kwargs):
        # Generate the code for the barcode (e.g. RDC2009092701)
        date = datetime.datetime.today()
        letters = ""
        words = self.name.split()
        for word in words:
            letters += word[0]
        self.code = f"{letters.upper()}{date.year}{date.month}{date.day}{date.hour}{date.minute}{date.second}"

        # Generate the duration from the poured_data
        diff = self.done_date - self.sampling_date
        self.dilate = diff.days

        super(Equivalent, self).save(*args, **kwargs)
    
    def __str__(self):
        return f"Valor Equivalente Arena Finos {self.id}"


class Equiv(models.Model):
    max_size        = models.FloatField(default=4.75)
    start_sat_time  = models.TimeField(default=datetime.time(00,00)) 
    out_sat_time    = models.TimeField(default=datetime.time(00,00))
    start_dec_time  = models.TimeField(default=datetime.time(00,00))
    out_dec_time    = models.TimeField(default=datetime.time(00,00))
    max_high_fine   = models.FloatField()
    max_high_sand   = models.FloatField()
    equiv_sand      = models.FloatField(editable=False)
    equivalent  = models.ForeignKey(Equivalent, on_delete=models.CASCADE)
    equipment   = models.ManyToManyField(Equip)
    tool        = models.ManyToManyField(Tool)    

    def save(self, *args, **kwargs):
        equiv_sand = self.max_high_sand / self.max_high_fine * 100.0
        self.equiv_sand = math.ceil(equiv_sand)
        
        super(Equiv, self).save(*args, **kwargs)

    def __str__(self):
        return f"Equiv {self.id}"

tests_soil/views/general_tests_soil.py
from django.shortcuts import render

def tests_soil_info_view(request):
    context = {
        "title": "Mecánica de Suelos Información",
    }
    return render(request, 'tests_soil/info_tests_soil.html', context)


def tests_soil_equips_view(request):
    context = {
        "title": "Mecánica de Suelos Equipos",
    }
    return render(request, 'tests_soil/equips_tests_soil.html', context)


def tests_soil_guides_view(request):
    context = {
        "title": "Mecánica de Suelos Guias de los Ensayos",
    }
    return render(request, 'tests_soil/guides_tests_soil.html', context)


def tests_soil_teachers_view(request):
    context = {
        "title": "Mecánica de Suelos Plana Docente",
    }
    return render(request, 'tests_soil/teachers_tests_soil.html', context)

templates/tests_soil/equivalent/equiv_form.html
{% extends 'tests_soil/base_tests_soil.html' %}
{% load crispy_forms_tags %}

{% block soil %}
<div class="row">
    <div class="col-sm-9 col-lg-12 mx-auto my-3">
        <div class="card shadow">
            <div class="card-body">
                <span class="table-add float-right">
                    <a href="{% url 'tests_soil:equivalent_list' %}" class="text-primary">
                        <i class="fas fa-times fa-1x" aria-hidden="true"></i>
                    </a>
                </span>
                <h4 class="h4-responsive font-weight-bold text-center ">{{ title }}</h4>
                <hr class="my-3">

                <form 
                    action="{% url 'tests_soil:equiv_save' obj.id %}" 
                    method="POST">
                    <div>
                        <div class="row">
                        {% csrf_token %}
                        {{ formset.management_form }}
                        {% for form in formset %}
                            <div class="col-md-6 col-lg-4">
                                <h6 class="h6-responsive font-weight-bold text-left ">Ensayo {{ forloop.counter }}</h6>
                                {{ form|crispy }}
                                <hr class="my-3">
                            </div>
                            {% endfor %}
                        </div>
                        <div class="mt-5">
                            <button class="btn btn-primary btn-block" name="submit" type="submit">Crear Ensayos</button>
                            <a href="{% url 'tests_soil:equivalent_list' %}" class="btn btn-primary btn-block" type="button">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/tests_soil/equivalent/equivalent_detail.html
{% extends 'tests_soil/base_tests_soil.html' %}

{% block soil %}
<!-- Template for a Client -->
{% if obj.user.is_client %}
{% include 'tests_soil/equivalent/detail/client.html' %}
{% endif %}

<!-- Template for a Bach -->
{% if obj.user.is_bach %}
{% include 'tests_soil/equivalent/detail/bach.html' %}
{% endif %}

<!-- Template for a Student -->
{% if obj.user.is_group %}
{% include 'tests_soil/equivalent/detail/student.html' %}
{% endif %}
                                
{% endblock %}

templates/tests_soil/equivalent/equivalent_form.html
{% extends 'tests_soil/base_tests_soil.html' %}
{% load crispy_forms_tags %}

{% block soil %}
<div class="row">
    <div class="col-md-6 mx-auto my-3">
        <div class="card shadow">
            <div class="card-body">
                <h4 class="h4-responsive font-weight-bold text-center ">{{ title }}</h4>
                <hr class="my-3">

                <span class="table-add float-right">
                    <a href="{% url 'tests_soil:equivalent_list' %}" class="text-primary">
                        <i class="fas fa-times fa-1x" aria-hidden="true"></i>
                    </a>
                </span>
                {% if obj %}
                <form 
                    id="equivalentForm" 
                    data-ref-per-url="{% url 'reference_person:ajax_reference_person' %}" 
                    data-const-url="{% url 'construction:ajax_construction' %}"
                    action="{% url 'tests_soil:equivalent_update' obj.id %}" 
                    method="POST">
                {% else %}
                <form 
                    id="equivalentForm" 
                    data-ref-per-url="{% url 'reference_person:ajax_reference_person' %}" 
                    data-const-url="{% url 'construction:ajax_construction' %}"
                    action="{% url 'tests_soil:equivalent_create' %}" 
                    method="POST">
                {% endif %}
                    <div>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="mt-5">
                            {% if obj %}
                            <button class="btn btn-primary btn-block" name="submit" type="submit">Editar Ensayo</button>
                            {% else %}
                            <button class="btn btn-primary btn-block" name="submit" type="submit">Crear Ensayo y Sigiente Paso</button>
                            {% endif %}
                            <a href="{% url 'tests_soil:equivalent_list' %}" class="btn btn-primary btn-block" type="button">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    $( function() {
      $( ".datepicker" ).datepicker();
    } );
</script>
<script>
    $("#id_user").change(function () {
    
      var url = $("#equivalentForm").attr("data-ref-per-url");  // get the url of the `load_cities` view
      var userId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'user': userId       // add the country id to the GET parameters
        },

        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_reference_person").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });
    });
</script>  
<script>
    $("#id_user").change(function () {
    
      var url = $("#equivalentForm").attr("data-const-url");  // get the url of the `load_cities` view
      var userId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'user': userId       // add the country id to the GET parameters
        },

        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_construction").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });
    });
</script>  
{% endblock %}

templates/tests_soil/equivalent/equivalent_list.html
{% extends 'tests_soil/base_tests_soil.html' %}

{% block soil %}
<!-- Section: Blog v.3 -->
<section class="my-3">

    <!-- Section heading -->
    <h2 class="h2-responsive font-weight-bold text-center my-4">{{ title }}</h2>
    <!-- Section description -->
    <p class="text-center dark-grey-text w-responsive mx-auto mb-5">Duis aute irure dolor in reprehenderit in
      voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    
    <!-- Grid row -->
    <div class="row">
    
        <!-- Grid column -->
        <div class="col-lg-5 col-xl-4">
        
          <!-- Featured image -->
          <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
            <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Others/images/49.jpg" alt="Sample image">
            <a>
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
        
        </div>
        <!-- Grid column -->
      
        <!-- Grid column -->
        <div class="col-lg-7 col-xl-8">
        
          <!-- Post title -->
          <h3 class="font-weight-bold mb-3"><strong>Descripción</strong></h3>
          <!-- Excerpt -->
          <p class="dark-grey-text">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit
            quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus
            et aut officiis debitis cum soluta nobis est eligendi placeat facere aut rerum.</p>
          <!-- Post data -->
          <p>by <a class="font-weight-bold">Jessica Clark</a>, 19/04/2018</p>
          <!-- Read more button -->
          <a data-toggle="tooltip" title="Descargar PDF" role="button" class="btn btn-primary btn-md"><i class="fas fa-file-download mr-2"></i>Manual</a>
        </div>
        <!-- Grid column -->  
    </div>
    <!-- Grid row -->
</section>
<!-- Section: Blog v.3 -->

<hr class="my-5">

<section class="my-3">
    <!-- Editable table -->
    <div class="card">
      <h4 class="h4-responsive card-header text-center font-weight-bold text-uppercase py-4">{{ title }}</h4>
      <div class="card-body">
        <div>
          {% if request.user.is_superuser or request.user.is_group or request.user.is_bach or request.user.is_admin %}
          <span class="table-add float-right mb-3 mr-2">
            <a href="{% url 'tests_soil:equivalent_create' %}" class="text-primary">
              <i class="fas fa-plus fa-2x" aria-hidden="true"></i>
            </a>
          </span>
          {% endif %}
          <table id="equivalentTable" class="display compact table table-bordered table-responsive table-striped text-center">
            <thead class="primary-color-dark white-text">
              <tr>
                <th rowspan="2">Usuario</th>
                <th rowspan="2">Id</th>
                <th colspan="3">Item</th>
                <th colspan="2">Fecha</th>
                <th rowspan="2">Tiempo de Espera (días)</th>
                <th rowspan="2">Acciones</th>
              </tr>
              <tr>
                <th>Calicata</th>
                <th>Estrato</th>
                <th>Código</th>
                <th>Muestreo</th>
                <th>Ensayo</th>
              </tr>
            </thead>
            <tbody>
              {% for obj in obj_list %}
              <tr>
                <td>{{ obj.user.username }}</td>
                <td>{{ obj.id }}</td>
                <td>{{ obj.pit }}</td>
                <td>{{ obj.layer }}</td>
                <td>{{ obj.code }}</td>
                <td>{{ obj.sampling_date|date:"d/m/Y" }}</td>
                <td>{{ obj.done_date|date:"d/m/Y" }}</td>
                <td>{{ obj.dilate }}</td>
                <td>
                  <div class="btn-group" role="group" aria-label="Basic example">
                    <a
                      href="{% url 'tests_soil:equiv_save' obj.id %}"
                      data-toggle="tooltip" title="Editar o Crear Lecturas" role="button" class="btn btn-dark btn-sm px-2 mx-1"><i class="fas fa-plus"></i>
                    </a>
                    <a
                      href="{% url 'tests_soil:equivalent_detail' obj.id %}"
                      data-toggle="tooltip" title="Detalles" role="button" class="btn btn-primary btn-sm px-2 mx-1"><i class="far fa-eye"></i>
                    </a>
                    {% if request.user.is_superuser or request.user.is_group or request.user.is_bach or request.user.is_admin %}
                    <a 
                      href="{% url 'tests_soil:equivalent_update' obj.id %}" 
                      data-toggle="tooltip" title="Editar" role="button" class="btn btn-success btn-sm px-2 mx-1"><i class="fas fa-edit"></i>
                    </a>
                    <a 
                      href="{% url 'tests_soil:equivalent_delete' obj.id %}"
                      data-toggle="tooltip" title="Borrar" role="button" class="btn btn-danger btn-sm px-2 mx-1"><i class="fas fa-trash"></i>
                    </a>
                    <a 
                      href="{% url 'tests_soil:equivalent_pdf' obj.id %}" 
                      data-toggle="tooltip" title="Descargar PDF" role="button" class="btn btn-orange btn-sm px-2 mx-1"><i class="far fa-file-pdf"></i>
                    </a>
                    {% endif %}
                  </div>
                </td>
              </tr>
              {% endfor %}
              <!-- This is our clonable table line -->
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- Editable table -->
</section>

{% endblock %}
{% block js %}
<script>
  $(document).ready( function () {
    $('#equivalentTable').DataTable({
      "scrollX": true,
      dom: 'B<"clear">lfrtip',
      buttons: [
          'csv', 'excel',
          {
            extend: 'pdfHtml5',
            orientation: 'landscape',
            pageSize: 'LEGAL',
            filename: '{{ file_name }}_{{ user.username }}_{{ obj_list.count }}'
          }
      ]
    });
  } );
</script>
{% endblock %}